"""add is_pre_mix column in formula table

Revision ID: 01b1e55c6efd
Revises: 2c7acf35e809
Create Date: 2026-08-18 15:30:49.284451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b1e55c6efd'
down_revision: Union[str, Sequence[str], None] = '2c7acf35e809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('is_pre_mix', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'is_pre_mix')
    # ### end Alembic commands ###
