"""change production order status values

Revision ID: 055b75f7686a
Revises: 8fb29df95919
Create Date: 2026-08-20 09:13:18.747715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '055b75f7686a'
down_revision: Union[str, Sequence[str], None] = '8fb29df95919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_options = ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')
new_options = sorted(('PENDING', 'MIXED', 'DELIVERED', 'CANCELLED'))

old_type = sa.Enum(*old_options, name='productionorderstatus')
new_type = sa.Enum(*new_options, name='productionorderstatus')
tmp_type = sa.Enum(*new_options, name='_productionorderstatus')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE production_orders ALTER COLUMN status TYPE _productionorderstatus'
               ' USING status::text::_productionorderstatus')
    old_type.drop(op.get_bind(), checkfirst=False)
    new_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE production_orders ALTER COLUMN status TYPE productionorderstatus'
               ' USING status::text::productionorderstatus')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE production_orders ALTER COLUMN status TYPE _productionorderstatus'
               ' USING status::text::_productionorderstatus')
    new_type.drop(op.get_bind(), checkfirst=False)
    old_type.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE production_orders ALTER COLUMN status TYPE productionorderstatus'
               ' USING status::text::productionorderstatus')
    tmp_type.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
