"""add bottle color and rename name to description

Revision ID: 1dabf22b4b1d
Revises: 7c6ab71a0b0b
Create Date: 2026-08-19 09:53:18.517507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dabf22b4b1d'
down_revision: Union[str, Sequence[str], None] = '7c6ab71a0b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bottle_color_enum = sa.Enum('CLEAR', 'WHITE', 'BLACK', name='bottlecolor')
    bottle_color_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eliquids', sa.Column('description', sa.String(length=255), nullable=False))
    op.add_column('eliquids', sa.Column('bottle_color', sa.Enum('CLEAR', 'WHITE', 'BLACK', name='bottlecolor'), nullable=True))
    op.drop_column('eliquids', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eliquids', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('eliquids', 'bottle_color')
    op.drop_column('eliquids', 'description')
    # ### end Alembic commands ###
    
    sa.Enum(name='bottlecolor').drop(op.get_bind(), checkfirst=True)
