"""remove nullable attribute from flavoring_option_id column

Revision ID: 25fd76ab87ca
Revises: a139f613e40d
Create Date: 2026-08-12 15:33:30.132620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fd76ab87ca'
down_revision: Union[str, Sequence[str], None] = 'a139f613e40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flavorings', 'flavoring_option_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flavorings', 'flavoring_option_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
