"""initial

Revision ID: 2c7acf35e809
Revises: 
Create Date: 2026-08-18 14:46:44.515727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7acf35e809'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavoring_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_vg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavoring_options_slug'), 'flavoring_options', ['slug'], unique=True)
    op.create_table('formulas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('chill_type', sa.Enum('CHILLED', 'NON_CHILLED', name='chilltype'), nullable=False),
    sa.Column('nic_type', sa.Enum('SALT', 'FREEBASE', name='nictype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_slug'), 'formulas', ['slug'], unique=True)
    op.create_table('nic_base_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_vg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nic_base_options_code'), 'nic_base_options', ['code'], unique=True)
    op.create_table('eliquids',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upc', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('chill_type', sa.Enum('CHILLED', 'NON_CHILLED', name='chilltype'), nullable=False),
    sa.Column('nic_type', sa.Enum('SALT', 'FREEBASE', name='nictype'), nullable=False),
    sa.Column('size', sa.Enum('ML_30', 'ML_60', 'ML_120', name='sizeoption'), nullable=False),
    sa.Column('nic_level', sa.Enum('MG_0', 'MG_3', 'MG_5', 'MG_6', 'MG_10', 'MG_12', 'MG_15', 'MG_18', 'MG_20', 'HIT_35', 'HIT_50', name='nicleveloption'), nullable=False),
    sa.Column('formula_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eliquids_upc'), 'eliquids', ['upc'], unique=True)
    op.create_table('nic_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formula_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_old_mix', sa.Boolean(), nullable=False),
    sa.Column('target_nic_str', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('target_vg', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('target_pg', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('nic_base_nic_str', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nic_profiles_slug'), 'nic_profiles', ['slug'], unique=True)
    op.create_table('flavorings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nic_profile_id', sa.Uuid(), nullable=False),
    sa.Column('flavoring_option_id', sa.Uuid(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['flavoring_option_id'], ['flavoring_options.id'], ),
    sa.ForeignKeyConstraint(['nic_profile_id'], ['nic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nic_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nic_profile_id', sa.Uuid(), nullable=False),
    sa.Column('nic_base_option_id', sa.Uuid(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['nic_base_option_id'], ['nic_base_options.id'], ),
    sa.ForeignKeyConstraint(['nic_profile_id'], ['nic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nic_bases')
    op.drop_table('flavorings')
    op.drop_index(op.f('ix_nic_profiles_slug'), table_name='nic_profiles')
    op.drop_table('nic_profiles')
    op.drop_index(op.f('ix_eliquids_upc'), table_name='eliquids')
    op.drop_table('eliquids')
    op.drop_index(op.f('ix_nic_base_options_code'), table_name='nic_base_options')
    op.drop_table('nic_base_options')
    op.drop_index(op.f('ix_formulas_slug'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_flavoring_options_slug'), table_name='flavoring_options')
    op.drop_table('flavoring_options')
    # ### end Alembic commands ###
