"""add flavoring_options table

Revision ID: 3bd8a28024ef
Revises: ef68c53ad83a
Create Date: 2026-08-12 14:07:57.115280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd8a28024ef'
down_revision: Union[str, Sequence[str], None] = 'ef68c53ad83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flavoring_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_vg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavoring_options_slug'), 'flavoring_options', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flavoring_options_slug'), table_name='flavoring_options')
    op.drop_table('flavoring_options')
    # ### end Alembic commands ###
