"""make is_old_mix column non-nullable

Revision ID: 3dbe1b17450b
Revises: c6eee461075c
Create Date: 2026-08-13 13:58:46.438234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dbe1b17450b'
down_revision: Union[str, Sequence[str], None] = 'c6eee461075c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nic_profiles', 'is_old_mix',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nic_profiles', 'is_old_mix',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
