"""add production order number

Revision ID: 44df79f637f1
Revises: cef6468fab0a
Create Date: 2026-09-15 11:37:37.481070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44df79f637f1'
down_revision: Union[str, Sequence[str], None] = 'cef6468fab0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_order_mix_jobs', sa.Column('production_order_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_production_order_mix_jobs_production_order_number'), 'production_order_mix_jobs', ['production_order_number'], unique=False)
    op.add_column('production_order_repat_jobs', sa.Column('production_order_number', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_production_order_repat_jobs_production_order_number'), 'production_order_repat_jobs', ['production_order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_order_repat_jobs_production_order_number'), table_name='production_order_repat_jobs')
    op.drop_column('production_order_repat_jobs', 'production_order_number')
    op.drop_index(op.f('ix_production_order_mix_jobs_production_order_number'), table_name='production_order_mix_jobs')
    op.drop_column('production_order_mix_jobs', 'production_order_number')
    # ### end Alembic commands ###
