"""create formulas, nic_profiles, nic_base_options, nic_bases, flavorings

Revision ID: 47a0cedab267
Revises: 
Create Date: 2026-08-10 14:06:57.303838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a0cedab267'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('chill_type', sa.Enum('CHILLED', 'NON_CHILLED', name='chilltype'), nullable=False),
    sa.Column('nic_type', sa.Enum('SALT', 'FREEBASE', name='nictype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_slug'), 'formulas', ['slug'], unique=True)
    op.create_table('nic_base_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_vg', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nic_base_options_code'), 'nic_base_options', ['code'], unique=True)
    op.create_table('nic_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('formula_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('full_description', sa.String(), nullable=True),
    sa.Column('is_new_mix', sa.Boolean(), nullable=False),
    sa.Column('target_nic_strength_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('target_vg_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('target_pg_ratio', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('nic_base_nic_strength', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formula_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nic_profiles_slug'), 'nic_profiles', ['slug'], unique=True)
    op.create_table('flavorings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nic_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_vg', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nic_profile_id'], ['nic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nic_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nic_profile_id', sa.Uuid(), nullable=False),
    sa.Column('nic_base_option_id', sa.Uuid(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['nic_base_option_id'], ['nic_base_options.id'], ),
    sa.ForeignKeyConstraint(['nic_profile_id'], ['nic_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nic_bases')
    op.drop_table('flavorings')
    op.drop_index(op.f('ix_nic_profiles_slug'), table_name='nic_profiles')
    op.drop_table('nic_profiles')
    op.drop_index(op.f('ix_nic_base_options_code'), table_name='nic_base_options')
    op.drop_table('nic_base_options')
    op.drop_index(op.f('ix_formulas_slug'), table_name='formulas')
    op.drop_table('formulas')
    # ### end Alembic commands ###
