"""add production order activity logs table

Revision ID: 4944ae987ead
Revises: 055b75f7686a
Create Date: 2026-08-20 10:56:12.343970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4944ae987ead'
down_revision: Union[str, Sequence[str], None] = '055b75f7686a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order_activity_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('production_order_id', sa.Uuid(), nullable=False),
    sa.Column('activity', sa.Enum('CREATED', 'ADJUST_QUANTITY', 'CHANGE_STATUS', 'SWITCH_PRIORITY', name='productionorderactivity'), nullable=False),
    sa.Column('old_value', sa.String(length=20), nullable=True),
    sa.Column('new_value', sa.String(length=20), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_order_activity_logs')
    # ### end Alembic commands ###
