"""add indexing to id columns

Revision ID: 4dc4881bd2e0
Revises: 38157e9cbbe5
Create Date: 2026-09-02 16:38:54.253392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc4881bd2e0'
down_revision: Union[str, Sequence[str], None] = '38157e9cbbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_eliquids_nic_profile_id'), 'eliquids', ['nic_profile_id'], unique=False)
    op.create_index(op.f('ix_flavorings_flavoring_option_id'), 'flavorings', ['flavoring_option_id'], unique=False)
    op.create_index(op.f('ix_flavorings_nic_profile_id'), 'flavorings', ['nic_profile_id'], unique=False)
    op.create_index(op.f('ix_nic_bases_nic_base_option_id'), 'nic_bases', ['nic_base_option_id'], unique=False)
    op.create_index(op.f('ix_nic_bases_nic_profile_id'), 'nic_bases', ['nic_profile_id'], unique=False)
    op.create_index(op.f('ix_nic_profiles_formula_id'), 'nic_profiles', ['formula_id'], unique=False)
    op.create_index(op.f('ix_production_order_activity_logs_production_order_id'), 'production_order_activity_logs', ['production_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_order_activity_logs_production_order_id'), table_name='production_order_activity_logs')
    op.drop_index(op.f('ix_nic_profiles_formula_id'), table_name='nic_profiles')
    op.drop_index(op.f('ix_nic_bases_nic_profile_id'), table_name='nic_bases')
    op.drop_index(op.f('ix_nic_bases_nic_base_option_id'), table_name='nic_bases')
    op.drop_index(op.f('ix_flavorings_nic_profile_id'), table_name='flavorings')
    op.drop_index(op.f('ix_flavorings_flavoring_option_id'), table_name='flavorings')
    op.drop_index(op.f('ix_eliquids_nic_profile_id'), table_name='eliquids')
    # ### end Alembic commands ###
