"""add ASSIGN_JOB po activity

Revision ID: 547528b8cde7
Revises: 9c110e1f7c5e
Create Date: 2026-09-14 13:35:03.800791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547528b8cde7'
down_revision: Union[str, Sequence[str], None] = '9c110e1f7c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE productionorderactivity ADD VALUE IF NOT EXISTS 'ASSIGN_JOB'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
