"""fix ratios to accept 1 whole number and 5 decimal digits

Revision ID: 59cba013fdd1
Revises: afb7b02755fe
Create Date: 2026-09-08 16:10:30.757970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59cba013fdd1'
down_revision: Union[str, Sequence[str], None] = 'afb7b02755fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flavorings', 'ratio',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_bases', 'ratio',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_nic_str',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_vg',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_pg',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'nic_base_nic_str',
               existing_type=sa.NUMERIC(precision=6, scale=3),
               type_=sa.Numeric(precision=1, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nic_profiles', 'nic_base_nic_str',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_pg',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_vg',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_nic_str',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=3),
               existing_nullable=False)
    op.alter_column('nic_bases', 'ratio',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    op.alter_column('flavorings', 'ratio',
               existing_type=sa.Numeric(precision=1, scale=5),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
