"""refactor put is_pre_mix column to nic profile instead of formula

Revision ID: 5bf7187b3d43
Revises: ef3ff5b79e9d
Create Date: 2026-08-18 15:38:23.359693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf7187b3d43'
down_revision: Union[str, Sequence[str], None] = 'ef3ff5b79e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formulas', 'is_pre_mix')
    op.add_column('nic_profiles', sa.Column('is_pre_mix', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nic_profiles', 'is_pre_mix')
    op.add_column('formulas', sa.Column('is_pre_mix', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
