"""add flavoring_options column to flavorings

Revision ID: 62aa3025d166
Revises: 3bd8a28024ef
Create Date: 2026-08-12 14:48:53.711367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62aa3025d166'
down_revision: Union[str, Sequence[str], None] = '3bd8a28024ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavorings', sa.Column('flavoring_option_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'flavorings', 'flavoring_options', ['flavoring_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flavorings', type_='foreignkey')
    op.drop_column('flavorings', 'flavoring_option_id')
    # ### end Alembic commands ###
