"""add production order table

Revision ID: 6a07ae420975
Revises: dc6ff99da581
Create Date: 2026-08-18 16:25:41.937770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a07ae420975'
down_revision: Union[str, Sequence[str], None] = 'dc6ff99da581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('eliquid_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='productionorderstatus'), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eliquid_id'], ['eliquids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_orders_order_number'), 'production_orders', ['order_number'], unique=True)
    op.add_column('eliquids', sa.Column('nic_profile_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('eliquids_formula_id_fkey'), 'eliquids', type_='foreignkey')
    op.create_foreign_key(None, 'eliquids', 'nic_profiles', ['nic_profile_id'], ['id'])
    op.drop_column('eliquids', 'formula_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eliquids', sa.Column('formula_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'eliquids', type_='foreignkey')
    op.create_foreign_key(op.f('eliquids_formula_id_fkey'), 'eliquids', 'formulas', ['formula_id'], ['id'])
    op.drop_column('eliquids', 'nic_profile_id')
    op.drop_index(op.f('ix_production_orders_order_number'), table_name='production_orders')
    op.drop_table('production_orders')
    # ### end Alembic commands ###
