"""add production order counter

Revision ID: 7c6ab71a0b0b
Revises: 6a07ae420975
Create Date: 2026-08-18 16:42:34.289539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6ab71a0b0b'
down_revision: Union[str, Sequence[str], None] = '6a07ae420975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order_counters',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_order_counters')
    # ### end Alembic commands ###
