"""rename quantity to ordered_quantity and add fulfilled_quantity

Revision ID: 7cf366993a88
Revises: 44df79f637f1
Create Date: 2026-09-22 16:36:05.454482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf366993a88'
down_revision: Union[str, Sequence[str], None] = '44df79f637f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('ordered_quantity', sa.Integer(), nullable=True))
    op.add_column('production_orders', sa.Column('fulfilled_quantity', sa.Integer(), nullable=True))
    op.drop_column('production_orders', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('production_orders', 'fulfilled_quantity')
    op.drop_column('production_orders', 'ordered_quantity')
    # ### end Alembic commands ###
