"""refactor activity log production_order_id column to cascade on delete

Revision ID: 7fdad52aa086
Revises: 91dab53ae01b
Create Date: 2026-08-21 15:12:58.392402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdad52aa086'
down_revision: Union[str, Sequence[str], None] = '91dab53ae01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('production_order_activity_logs_production_order_id_fkey'), 'production_order_activity_logs', type_='foreignkey')
    op.create_foreign_key('production_order_activity_logs_production_order_id_fkey', 'production_order_activity_logs', 'production_orders', ['production_order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('production_order_activity_logs_production_order_id_fkey', 'production_order_activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('production_order_activity_logs_production_order_id_fkey'), 'production_order_activity_logs', 'production_orders', ['production_order_id'], ['id'])
    # ### end Alembic commands ###
