"""refactor FK ondeletes

Revision ID: 8d2e25547b64
Revises: 7fdad52aa086
Create Date: 2026-08-21 15:19:31.479328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2e25547b64'
down_revision: Union[str, Sequence[str], None] = '7fdad52aa086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('eliquids_nic_profile_id_fkey'), 'eliquids', type_='foreignkey')
    op.create_foreign_key('eliquids_nic_profile_id_fkey', 'eliquids', 'nic_profiles', ['nic_profile_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('flavorings_nic_profile_id_fkey'), 'flavorings', type_='foreignkey')
    op.create_foreign_key('flavorings_nic_profile_id_fkey', 'flavorings', 'nic_profiles', ['nic_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('nic_bases_nic_profile_id_fkey'), 'nic_bases', type_='foreignkey')
    op.create_foreign_key('nic_bases_nic_profile_id_fkey', 'nic_bases', 'nic_profiles', ['nic_profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('nic_profiles_formula_id_fkey'), 'nic_profiles', type_='foreignkey')
    op.create_foreign_key('nic_profiles_formula_id_fkey', 'nic_profiles', 'formulas', ['formula_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nic_profiles_formula_id_fkey', 'nic_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('nic_profiles_formula_id_fkey'), 'nic_profiles', 'formulas', ['formula_id'], ['id'])
    op.drop_constraint('nic_bases_nic_profile_id_fkey', 'nic_bases', type_='foreignkey')
    op.create_foreign_key(op.f('nic_bases_nic_profile_id_fkey'), 'nic_bases', 'nic_profiles', ['nic_profile_id'], ['id'])
    op.drop_constraint('flavorings_nic_profile_id_fkey', 'flavorings', type_='foreignkey')
    op.create_foreign_key(op.f('flavorings_nic_profile_id_fkey'), 'flavorings', 'nic_profiles', ['nic_profile_id'], ['id'])
    op.drop_constraint('eliquids_nic_profile_id_fkey', 'eliquids', type_='foreignkey')
    op.create_foreign_key(op.f('eliquids_nic_profile_id_fkey'), 'eliquids', 'nic_profiles', ['nic_profile_id'], ['id'])
    # ### end Alembic commands ###
