"""make bottle color non-nullable

Revision ID: 8fb29df95919
Revises: 1dabf22b4b1d
Create Date: 2026-08-19 13:48:43.088986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb29df95919'
down_revision: Union[str, Sequence[str], None] = '1dabf22b4b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eliquids', 'bottle_color',
               existing_type=postgresql.ENUM('CLEAR', 'WHITE', 'BLACK', name='bottlecolor'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eliquids', 'bottle_color',
               existing_type=postgresql.ENUM('CLEAR', 'WHITE', 'BLACK', name='bottlecolor'),
               nullable=True)
    # ### end Alembic commands ###
