"""make ProductionOrderMixJob recipe columns nullable

Revision ID: 9c110e1f7c5e
Revises: fcee8ca51c7f
Create Date: 2026-09-14 13:18:51.985484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c110e1f7c5e'
down_revision: Union[str, Sequence[str], None] = 'fcee8ca51c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_order_mix_jobs', 'recipe_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('production_order_mix_jobs', 'total_volume_ml',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('production_order_mix_jobs', 'total_weight_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_order_mix_jobs', 'total_weight_g',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('production_order_mix_jobs', 'total_volume_ml',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('production_order_mix_jobs', 'recipe_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
