"""remove name and is_vg columns from flavorings

Revision ID: a139f613e40d
Revises: 62aa3025d166
Create Date: 2026-08-12 15:30:46.847843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a139f613e40d'
down_revision: Union[str, Sequence[str], None] = '62aa3025d166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flavorings', 'is_vg')
    op.drop_column('flavorings', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flavorings', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('flavorings', sa.Column('is_vg', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
