"""fix ratios to accept 1 whole number and 10 decimal digits

Revision ID: ae63a630ef6b
Revises: 59cba013fdd1
Create Date: 2026-09-08 16:16:15.627831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae63a630ef6b'
down_revision: Union[str, Sequence[str], None] = '59cba013fdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flavorings', 'ratio',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    op.alter_column('nic_bases', 'ratio',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_nic_str',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_vg',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_pg',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'nic_base_nic_str',
               existing_type=sa.NUMERIC(precision=1, scale=5),
               type_=sa.Numeric(precision=1, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nic_profiles', 'nic_base_nic_str',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_pg',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_vg',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_profiles', 'target_nic_str',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('nic_bases', 'ratio',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    op.alter_column('flavorings', 'ratio',
               existing_type=sa.Numeric(precision=1, scale=10),
               type_=sa.NUMERIC(precision=1, scale=5),
               existing_nullable=False)
    # ### end Alembic commands ###
