"""add TOGGLE_ARCHIVED activity name

Revision ID: afb7b02755fe
Revises: 4dc4881bd2e0
Create Date: 2026-09-02 16:44:15.574164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb7b02755fe'
down_revision: Union[str, Sequence[str], None] = '4dc4881bd2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE productionorderactivity ADD VALUE IF NOT EXISTS 'TOGGLE_ARCHIVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
