"""add allocations

Revision ID: b4f44c27560c
Revises: 2a6ee82efc2f
Create Date: 2026-10-07 16:43:44.227691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f44c27560c'
down_revision: Union[str, Sequence[str], None] = '2a6ee82efc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('production_order_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_allocation_quantity_positive'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', 'location_id', name='uq_allocation_order_location')
    )
    op.create_index(op.f('ix_production_order_allocations_location_id'), 'production_order_allocations', ['location_id'], unique=False)
    op.create_index(op.f('ix_production_order_allocations_production_order_id'), 'production_order_allocations', ['production_order_id'], unique=False)
    op.add_column('locations', sa.Column('is_hq', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.create_index('uq_locations_single_hq', 'locations', ['is_hq'], unique=True, postgresql_where=sa.text('is_hq'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_locations_single_hq', table_name='locations', postgresql_where=sa.text('is_hq'))
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=False)
    op.drop_column('locations', 'is_hq')
    op.drop_index(op.f('ix_production_order_allocations_production_order_id'), table_name='production_order_allocations')
    op.drop_index(op.f('ix_production_order_allocations_location_id'), table_name='production_order_allocations')
    op.drop_table('production_order_allocations')
    # ### end Alembic commands ###
