"""rename is_new_mix column to is_old_mix

Revision ID: c6eee461075c
Revises: 25fd76ab87ca
Create Date: 2026-08-13 13:23:35.742161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6eee461075c'
down_revision: Union[str, Sequence[str], None] = '25fd76ab87ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nic_profiles', sa.Column('is_old_mix', sa.Boolean(), nullable=True))
    op.drop_column('nic_profiles', 'is_new_mix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nic_profiles', sa.Column('is_new_mix', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('nic_profiles', 'is_old_mix')
    # ### end Alembic commands ###
