"""change production order status data

Revision ID: cef6468fab0a
Revises: 547528b8cde7
Create Date: 2026-09-14 14:30:07.742695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef6468fab0a'
down_revision: Union[str, Sequence[str], None] = '547528b8cde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_options = ('PENDING', 'MIXED', 'DELIVERED', 'CANCELLED')
new_options = sorted(('PENDING', 'IN_PROGRESS', 'FULFILLED', 'DELIVERED', 'CANCELLED'))

old_type = sa.Enum(*old_options, name='productionorderstatus')
new_type = sa.Enum(*new_options, name='productionorderstatus')
tmp_type = sa.Enum(*new_options, name='_productionorderstatus')

def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  tmp_type.create(op.get_bind(), checkfirst=False)
  op.execute(
    'ALTER TABLE production_orders ALTER COLUMN status TYPE _productionorderstatus'
    ' USING status::text::_productionorderstatus'
  )
  old_type.drop(op.get_bind(), checkfirst=False)
  new_type.create(op.get_bind(), checkfirst=False)
  op.execute(
    'ALTER TABLE production_orders ALTER COLUMN status TYPE productionorderstatus'
    ' USING status::text::productionorderstatus'
  )
  tmp_type.drop(op.get_bind(), checkfirst=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  tmp_type.create(op.get_bind(), checkfirst=False)
  op.execute(
    'ALTER TABLE production_orders ALTER COLUMN status TYPE _productionorderstatus'
    ' USING status::text::_productionorderstatus'
  )
  new_type.drop(op.get_bind(), checkfirst=False)
  old_type.create(op.get_bind(), checkfirst=False)
  op.execute(
    'ALTER TABLE production_orders ALTER COLUMN status TYPE productionorderstatus'
    ' USING status::text::productionorderstatus'
  )
  tmp_type.drop(op.get_bind(), checkfirst=False)
  # ### end Alembic commands ###
