"""refactor is_pre_mix column to be non-nullable

Revision ID: dc6ff99da581
Revises: 5bf7187b3d43
Create Date: 2026-08-18 15:42:03.236857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6ff99da581'
down_revision: Union[str, Sequence[str], None] = '5bf7187b3d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
