"""make po quantity nullable

Revision ID: e95efdacf3d8
Revises: 0d4ed22bda2f
Create Date: 2026-09-10 16:00:08.421780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95efdacf3d8'
down_revision: Union[str, Sequence[str], None] = '0d4ed22bda2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
