"""refactor is_pre_mix column to be non-nullable

Revision ID: ef3ff5b79e9d
Revises: 01b1e55c6efd
Create Date: 2026-08-18 15:34:14.080361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3ff5b79e9d'
down_revision: Union[str, Sequence[str], None] = '01b1e55c6efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formulas', 'is_pre_mix',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('formulas', 'is_pre_mix',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
