"""drop NicProfile full_name column

Revision ID: fa72b390fbdb
Revises: 4944ae987ead
Create Date: 2026-08-21 09:41:16.200378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa72b390fbdb'
down_revision: Union[str, Sequence[str], None] = '4944ae987ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nic_profiles', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nic_profiles', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
