"""add production job tables

Revision ID: fcee8ca51c7f
Revises: e95efdacf3d8
Create Date: 2026-09-11 16:44:27.262460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcee8ca51c7f'
down_revision: Union[str, Sequence[str], None] = 'e95efdacf3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_order_mix_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('production_order_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('produced_quantity', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('recipe_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_volume_ml', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_weight_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'MIXED', 'REASSIGNED', name='productionordermixjobstatus'), nullable=False),
    sa.Column('is_priority', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_production_order_mix_jobs_one_active_per_order', 'production_order_mix_jobs', ['production_order_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_index(op.f('ix_production_order_mix_jobs_production_order_id'), 'production_order_mix_jobs', ['production_order_id'], unique=False)
    op.create_table('production_order_repat_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('production_order_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=True),
    sa.Column('incoming_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CANCELLED', 'COMPLETED', 'IN_PROGRESS', 'REASSIGNED', name='productionorderjobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_production_order_repat_jobs_one_active_per_order', 'production_order_repat_jobs', ['production_order_id'], unique=True, postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.create_index(op.f('ix_production_order_repat_jobs_production_order_id'), 'production_order_repat_jobs', ['production_order_id'], unique=False)
    
    job_enum = postgresql.ENUM('MIX', 'REPAT', name='productionorderjob', create_type=False)
    job_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('production_orders', sa.Column('job', job_enum, nullable=True))
    # op.add_column('production_orders', sa.Column('job', sa.Enum('MIX', 'REPAT', name='productionorderjob'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('production_orders', 'job')
    op.drop_index(op.f('ix_production_order_repat_jobs_production_order_id'), table_name='production_order_repat_jobs')
    op.drop_index('ix_production_order_repat_jobs_one_active_per_order', table_name='production_order_repat_jobs', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.drop_table('production_order_repat_jobs')
    op.drop_index(op.f('ix_production_order_mix_jobs_production_order_id'), table_name='production_order_mix_jobs')
    op.drop_index('ix_production_order_mix_jobs_one_active_per_order', table_name='production_order_mix_jobs', postgresql_where=sa.text("status = 'IN_PROGRESS'"))
    op.drop_table('production_order_mix_jobs')
    
    op.drop_column('production_orders', 'job')
    postgresql.ENUM(name='productionorderjob').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
